### ISSUE TITLE
docker-machine freezes

### ISSUE THREAD

**Issue by mjrgr** [xenserver/docker-machine-driver-xenserver#9]
Hi,

I have a problem when I try to start a new VM using docker-machine:

```
docker-machine --debug create -d xenserver --xenserver-server ***** --xenserver-username root --xenserver-password ******* --xenserver-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.12.3/boot2docker.iso --xenserver-memory-size 2048 test-vm
```

docker-machine freezes at this line
`(test-vm) Waiting for VM to start...`

But it works when I use 1.12.0 version of **boot2docker** iso file

**Comment by robertbreker** [comment]
Thanks for reporting this !

 I can't see any problem with v17.03.1-ce on XenServer 7.1.
Is this still a problem for you?

Best wishes,
Robert

**Comment by robertbreker** [comment]
Closing this issue for now - more than happy to reopen, if this problem is still seen.

**Comment by mjrgr** [comment]
Hi,

Nope, I didn't have the problem since I upgraded to boot2docker 1.12 and next versions...
Works fine on both XenServer 6.5 SP1 and 7.0, I haven't tested 7.1 yet.

Thank you
